### ISSUE TITLE
feat: Update Loculus submission with Pre-Signed S3 URLs

### ISSUE THREAD

**Issue by gordonkoehn** [cbg-ethz/sr2silo#214]
Loculus now implements pre-signed URLs. 

sr2silo in-built submission process needs to be updated to get the S3 URLs from the loculus instance. 

Currently, we submit an empty sequence file and a metadata file with an S3 link to a Loculus instance. 
Then the current [WisePulse](https://github.com/cbg-ethz/WisePulse) would download files from there.

Questions:
- How to set up the S3 Server for Loculus ? Can I supply an s3 bucket from AWS or else ?
- Where are the resources to understand the new submission process?

_____

Should be done after:

- #213

**Comment by fhennig** [comment]
Hey! Yeah we didn't get around to the docs yet, we really should! So yeah, you can use any S3 bucket. Once you have one, in your `values.yaml` configure:

```yaml
s3:
  enabled: true
  bucket:
    region: <region here>
    bucket: <bucket name here>
```

for the access key and secret key, you can do it directly in the `values.yaml` as well like this:

```yaml
secrets:
  s3-bucket:
    type: raw
    data:
      accessKey: "dummyAccessKey"
      secretKey: "dummySecretKey"
```

or better with a sealed secret:

```yaml
secrets:
  s3-bucket:
    type: sealedsecret
    clusterWide: "true"
    encryptedData:
      accessKey: AgCm73j1g21Dn....
      secretKey: AgAS8a/ldl....
```

The only other config on the bucket needs to be this config:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect":     "Allow",
      "Action":     "s3:GetObject",
      "Resource":    "arn:aws:s3:::<bucket name here>/*",
      "Principal":   "*",
      "Condition": {  "StringEquals": {"s3:ExistingObjectTag/public": "true" } }
    }
  ]
}

```

It is used to publish files.

To make it possible to submit files to an organism, enable the submission type like this:

```yaml
  dummy-organism-with-files:
    schema:
      submissionDataTypes:
        files:
          enabled: true
          categories:
            - name: raw_reads
      files:  # this is the output file section - probably you want that too
        - name: raw_reads
```

If that is configured, you'll see a new section in the submission form:

<img width="952" alt="Image" src="https://github.com/user-attachments/assets/ca955f31-4c1d-4421-a5c2-dc37b6831e1e" />

And in the sequence details view later on, there'll be a section for files:

<img width="448" alt="Image" src="https://github.com/user-attachments/assets/ee601dba-ef9e-48c9-a4e0-49bc60565720" />

I hope that clarifies some things! We'll do the proper docs soon I hope.
